### ISSUE TITLE
Image chooser has stopped working since Comfy update

### ISSUE THREAD

**Issue by Strontium99** [yolain/ComfyUI-Easy-Use#838]
Since a recent update the image chooser seems to not allow you to discard an image batch, nether by the Discard link that used to appear on the Chooser node, or via the Cancel current run icon to the top right. You can select an image (or images) and progress the image/s. But even after this completes the workflow says it at the easy imageChooser stage. You are unable to cancel the workflow. You have to restart the server to clear it.

In ComfyUI manager is says I'm on 1.3.1 of Easy Use. But in the settings > about screen it says I'm running 1.3.2.

I'm running ComfyUI 0.3.45 and Front end 1.25.0.

<img width="1476" height="158" alt="Image" src="https://github.com/user-attachments/assets/6f388ef4-cefe-4052-9b60-4ac86b68a88c" />
<img width="681" height="153" alt="Image" src="https://github.com/user-attachments/assets/6c369ac8-541b-4b03-a1fb-e9cb51d3b470" />
<img width="851" height="707" alt="Image" src="https://github.com/user-attachments/assets/1c9614bd-6f3c-45a5-beef-640e2fbcb0d0" />
<img width="842" height="685" alt="Image" src="https://github.com/user-attachments/assets/66b2a653-5a56-4c3e-8463-c8098a1884c8" />

**Comment by yolain** [comment]
I am unable to resolve with this issue. In front-end versions 1.24.2 and later, the value of `app.runningNodeId` is always `null`, making it impossible to determine whether the workflow has reached this node based on that value. Unfortunately, I currently do not have enough time to refactor this part of the code.

**Comment by yolain** [comment]
But there is currently a manual solution, which is to switch the mode to Keep Last Selection when running to that node. The process to continue normally.

**Comment by SQLSammy** [comment]
Today same problem, tried many things.

Solution: Reverted from nightly 1.3.2 to 1.3.1 and its back to work. 

Pressed Update all Nodes in Comfy and it stopped working. 

Definitly a regression from 1.3.1 to 1.3.2

**Comment by sacredbone** [comment]
@SQLSammy I did a full update (ComfyUI + All nodes) and can't confirm that, Image Chooser isn't working for me with 1.3.2 and 1.3.1 ...

@yolain It's really unfortunate having image chooser not working, it's one of the main reasons to use this custom node. I hope you can fix it. Thanks for your great work so far.

**Comment by yolain** [comment]
> [@SQLSammy](https://github.com/SQLSammy) I did a full update (ComfyUI + All nodes) and can't confirm that, Image Chooser isn't working for me with 1.3.2 and 1.3.1 ...
> 
> [@yolain](https://github.com/yolain) It's really unfortunate having image chooser not working, it's one of the main reasons to use this custom node. I hope you can fix it. Thanks for your great work so far.

Fixed last week, please update to the latest version.

**Comment by sacredbone** [comment]
@yolain I did and it seems to be not fixed, maybe it's a different bug? ComfyUI + All nodes are up to date, and I use 1.3.2

It doesn't work in my regular workflows and throws a lot of errors. 
So I tried it with the simple default workflow and it still doesn't work. 

- When I create 1 image it shows "Progress selected image as a restart", when I click it, the workflow is stuck.
- When I create a batch of multiple image and I select only one image it shows above message.
- When I create a batch of images and select multiple images, it shows i.e. "Progress selected (2/3)", when I choose this option workflow is stuck as well.

<img width="1604" height="726" alt="Image" src="https://github.com/user-attachments/assets/464cd35c-a87e-4560-b88f-93faf4429b8b" />


UPDATE: So I reinstalled it, which causes now a different behavior but the workflow is still stuck and I have to restart comfy. :/

**Comment by yolain** [comment]
> [@yolain](https://github.com/yolain) I did and it seems to be not fixed, maybe it's a different bug? ComfyUI + All nodes are up to date, and I use 1.3.2
> 
> It doesn't work in my regular workflows and throws a lot of errors. So I tried it with the simple default workflow and it still doesn't work.
> 
> * When I create 1 image it shows "Progress selected image as a restart", when I click it, the workflow is stuck.
> * When I create a batch of multiple image and I select only one image it shows above message.
> * When I create a batch of images and select multiple images, it shows i.e. "Progress selected (2/3)", when I choose this option workflow is stuck as well.
> 
> <img alt="Image" width="1604" height="726" src="https://private-user-images.githubusercontent.com/107143108/478643916-464cd35c-a87e-4560-b88f-93faf4429b8b.png?jwt=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3NTUzNjA3MzIsIm5iZiI6MTc1NTM2MDQzMiwicGF0aCI6Ii8xMDcxNDMxMDgvNDc4NjQzOTE2LTQ2NGNkMzVjLWE4N2UtNDU2MC1iODhmLTkzZmFmNDQyOWI4Yi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjUwODE2JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI1MDgxNlQxNjA3MTJaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0wOTE4ODg0ODE2MTViNmY1ZTdjZjZjNmFhYTEwZDM1NGU3MWFlNDZlZmY4MDVmOTQ2ZGVmYzg5YTZkYTQ0NjM4JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.BaesZzust3CMdww02XM-XwOGC0dguWEyI0ujbQxRbVs">
> UPDATE: So I reinstalled it, which causes now a different behavior but the workflow is still stuck and I have to restart comfy. :/

Your version is outdated. The latest version no longer has the "Progress selected image as restart"

**Comment by memedoggo** [comment]
comfy 3.5.0, this node 1.3.2
generating a single image 

"always pause"
when i click progress selected image nothing happens
and i can't even cancel the current queue

"keep last selection"
just working like i pressed progress selected image and progress automatically

**Comment by imHugoLeandro** [comment]
Im having the same issue, I tried to rollback to 1.3.1 and 1.3.0 didnt work.... And I cant cancel the run or anything, I need to restart the whole Comfyui

**Comment by Vik71it** [comment]
I'm experiencing the same problem here, 1.3.2 broke the image chooser node, reverting to 1.3.1 didn't work.

Had to uninstall the whole package and reinstall the 1.3.0 from scratch.

**Comment by stef654547** [comment]
switching to the nightly build of the node fixed the issue for me

**Comment by Vik71it** [comment]
> switching to the nightly build of the node fixed the issue for me

same here

**Comment by qvink** [comment]
This issue still persists for me. As above, the "Cancel" button does not appear and the run cannot be cancelled by any means, requiring a full ComfyUI restart.

I have updated absolutely everything I possibly could:
ComfyUI version: **0.3.54**
EasyUse version: **1.3.2**
FrontEnd version: **1.25.11**



<img width="309" height="191" alt="Image" src="https://github.com/user-attachments/assets/08664e62-ac2a-4bb4-aab9-231d06231a1c" />
<img width="493" height="97" alt="Image" src="https://github.com/user-attachments/assets/0f446e1e-ae1c-4205-96cf-21e527f4cc69" />

This image demonstrates the bug - the cancel button does not appear and the workflow cannot be cancelled.

<img width="1339" height="368" alt="Image" src="https://github.com/user-attachments/assets/a7b865b5-3a38-4c8f-aac6-392477fc2c90" />


And these are some errors that appeared in the browser console upon loading up a workflow using the image chooser:

<img width="897" height="502" alt="Image" src="https://github.com/user-attachments/assets/796f6f8f-a932-41c2-bf7f-cfba58824582" />

Please let me know if there is more information I can provide to assist in reproduction.

**Comment by Strontium99** [comment]
Hi all,

Not sure if this helps or not, but everything is working for me now.
WIndows 10 PC.
Python 3.12.8
ComfyUI 0.3.51
Frontend 1.26.7
EasyUse 1.3.3

I'm using ComfyUI Nightly Version when I update.
I'd suggest try updating your Frontend (https://github.com/Comfy-Org/ComfyUI_frontend)
