### ISSUE TITLE
Please fix to work with Partial Execution (ComfyUI_frontend v1.24)

### ISSUE THREAD

**Issue by christian-byrne** [yolain/ComfyUI-Easy-Use#844]
In this PR, we’ve changed the signature of queuePrompt: https://github.com/Comfy-Org/ComfyUI_frontend/pull/4624.

Could you update your patch to support the new signature? Currently, partial execution does not seem to work with Easy-Use installed.

In general, we recommend using `...arguments` or a form of introspection (e.g., `typeof`, `Reflect`, inspecting `arguments`, etc.) to avoid tightly coupling to a specific function signature.

**Comment by yolain** [comment]
I don’t fully understand how partial execution is supposed to work. I tested it by adding only a subgraph node to the default workflow and disabling all custom nodes, but it still executed all nodes in the workflow. 

https://github.com/user-attachments/assets/01ebbb26-659d-42c5-9615-6f106e2378d2

**Comment by christian-byrne** [comment]
I think you need to update ComfyUI for this PR:

- https://github.com/comfyanonymous/ComfyUI/pull/9123

In the description of https://github.com/Comfy-Org/ComfyUI_frontend/pull/4624, you can see a demo video.

**Comment by yolain** [comment]
> What version of ComfyUI and ComfyUI_frontend is that? Partial execution was updated on these two PRs:
> 
> * [Add support for partial execution in backend comfyanonymous/ComfyUI#9123](https://github.com/comfyanonymous/ComfyUI/pull/9123)
> * [[feat] Move partial execution to the backend and make work with subgraphs Comfy-Org/ComfyUI_frontend#4624](https://github.com/Comfy-Org/ComfyUI_frontend/pull/4624)
> 
> In the description of [Comfy-Org/ComfyUI_frontend#4624](https://github.com/Comfy-Org/ComfyUI_frontend/pull/4624), you can see a demo video.

Thanks, it's because my ComfyUI backend wasn't updated.  Now, it has been fixed.

**Comment by Nekodificador** [comment]
Hi @yolain just letting you know that this issue is back. Installing easy-use breaks the isolated execution again. I’m not sure why, but it’s the only node pack causing this in my whole setup

**Comment by yolain** [comment]
> Hi [@yolain](https://github.com/yolain) just letting you know that this issue is back. Installing easy-use breaks the isolated execution again. I’m not sure why, but it’s the only node pack causing this in my whole setup

I tried it out, and the partial execution works fine.
